# Generated by Django 2.0.5 on 2018-06-05 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('tumbnail', models.CharField(max_length=200)),
                ('isbn', models.BigIntegerField(primary_key='true', serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prestito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_loan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_loan_date', models.DateTimeField(blank=True, null=True)),
                ('books', models.ManyToManyField(to='webapp.Libro')),
                ('n_tessera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sinossi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('tumbnail', models.CharField(max_length=200)),
            ],
        ),
    ]
