# Generated by Django 2.0.6 on 2018-06-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_giavisto_prenotato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giavisto',
            name='books',
        ),
        migrations.RemoveField(
            model_name='giavisto',
            name='user',
        ),
        migrations.DeleteModel(
            name='GiaVisto',
        ),
    ]
