# Generated by Django 2.0.5 on 2018-05-24 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180521_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cognome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prestito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.BigIntegerField()),
                ('start_loan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_loan_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sinossi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('tumbnail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utenti',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('cognome', models.CharField(max_length=200)),
                ('n_tessera', models.AutoField(primary_key=True, serialize=False)),
                ('classe', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='prestito',
            name='n_tessera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Utenti'),
        ),
    ]
